### ISSUE TITLE
how do I stop the next function from getting executed?

### ISSUE THREAD

**Issue by detj** [dominictarr/map-stream#17]
Say, if there is a condition where the whole `.map()` should just exit without calling the subsequent `callback`. Is it possible to achieve that?

**Comment by detj** [comment]
Here's some code for context

```
fs
  .createReadStream(file)
  .pipe(es.map(function(data, cb) {

    // the connection dropped, so any future iteration is futile
    // how can I make it quit?
  }));
```

I tried doing these

`this.destroy()`
`this.end()`

But they don't seem to work

**Comment by dominictarr** [comment]
you mean the downstream connection? i.e. the thing you are pipeing this to?
it would be nice if errors propagated like that, and the source (in this case, createReadStream) was closed when the thing it was writing to died.

Error propagation is supported in [pull-stream](https://github.com/dominictarr/pull-stream) but not in node streams.

If you need to do that in node streams, you should call destroy on the source (the fs stream, not the map)

**Comment by detj** [comment]
Aha! I see what you are saying. No, not the downstream connection. I have a socket which can die any moment and once it dies, I need to stop the `es.map`.

So, I am listening for the `disconnect` event on the socket and I call `.destroy()` on the stream. Works like a charm now.

:+1:
